language: java
sudo: false

jdk:
- oraclejdk8
install:
- mvn package -Dmaven.test.skip=true
after_success:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify jacoco:report sonar:sonar coveralls:report
cache:
  directories:
  - $HOME/.m2/repository
notifications:
  email:
  - marcos.hgb@gmail.com