= Trade Bot
Marcos Barbero <marcos.hgb@gmail.com>
:toc:
:summary: Simple bot implementation to perform some trading operations.

== Overview
This application is a simple bot implementation to perform some trading operations. If you are really anxious to run the
application just skip everything and jump to the <<Build & Run>> section.

== Architecture & Design
This section describes this project architecture and design.

=== Technology Stack & Requirements

 * link:http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html[Java 8]
 * link:https://projects.spring.io/spring-boot/[Spring Boot]
 * link:http://projectlombok.org/features/index.html[Project Lombok]
 * link:https://maven.apache.org[Maven]

=== Packages

.Packages structure and content
[source,yaml]
----
com.marcosbarbero.tradebot // <1>
com.marcosbarbero.tradebot.commons // <2>
com.marcosbarbero.tradeboot.config // <3>
com.marcosbarbero.tradebot.model // <4>
com.marcosbarbero.tradebot.service // <5>
----
<1> Root package stores the StartUp class
<2> Utility classes
<3> Configuration files for the WebSocket connection and HTTP REST calls
<4> All the data model used in the application such as WebSocket response as well as the REST API response and the storage layer.
<5> Services and Handlers that execute the trading operations.

=== Configuration properties
The current implementation favors convention over configuration and is designed to get you up and running as quickly
as possible

.Externalized configuration properties
[source,yaml]
----
trade:
  api:
    endpoints:
      subscription: ws://localhost:8080/subscriptions/me  // <1>
      buy-order: http://localhost:8080/core/16/users/me/trades  // <2>
      sell-order: http://localhost:8080/core/16/users/me/portfolio/positions/  // <3>
    product-id: sb26493  // <4>
    buy-price: 11513.6  // <5>
    sell-price:
      lower-limit: 11500.6  // <6>
      upper-limit: 11553.6  // <7>
    headers:  // <8>
      Accept-Language: nl-NL,en;q=0.8
      Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyZWZyZXNoYWJsZSI6ZmFsc2UsInN1YiI6ImJiMGNkYTJiLWExMGUtNGVkMy1hZDVhLTBmODJiNGMxNTJjNCIsImF1ZCI6ImJldGEuZ2V0YnV4LmNvbSIsInNjcCI6WyJhcHA6bG9naW4iLCJydGY6bG9naW4iXSwiZXhwIjoxODIwODQ5Mjc5LCJpYXQiOjE1MDU0ODkyNzksImp0aSI6ImI3MzlmYjgwLTM1NzUtNGIwMS04NzUxLTMzZDFhNGRjOGY5MiIsImNpZCI6Ijg0NzM2MjI5MzkifQ.M5oANIi2nBtSfIfhyUMqJnex-JYg6Sm92KPYaUL9GKg
      Content-Type: application/json
      Accept: application/json
----
<1> WebSocket real-time feed subscription endpoint
<2> The endpoint to buy order (Make a Trade)
<3> The endpoint to sell order (Close Position)
<4> The product id to quote
<5> The buy price
<6> The lower limit price to sell
<7> The upper limit price to sell
<8> Map containing default HTTP Headers to be sent in all requests

==== Overriding default configuration properties
This section describes how to override this application properties.
As this application is built using link:https://projects.spring.io/spring-boot/[Spring Boot] given us the possibility
to override its properties in few ways.

 * Command line args +
 It's possible to override the properties in the command line application startup just adding the following arguments

 $ java -jar /path/to/trade-bot.jar --trade.api.product-id=$productId --trade.api.buy-price=$buyPrice --trade.api.sell-price.lower-limit=$lowerLimit --trade.api.sell-price.upper-limit=$upperLimit
 
 * Editing application properties file +
 It's possible to override the properties by editing the link:src/main/resources/application-yml[application.yml] file.

IMPORTANT: After editing the properties file it's necessary to <<Build & Run,build>> the application before run it.

[TIP]
====
Check link:https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html[spring-boot documentation]
for more details about externalizing configuration.
====

==== Profiles
Currently there are two available profiles in the application:

 * Default
 ** Calls the API in localhost
 ** There's no need to add any argument to run using the default profile
 * Beta
 ** Calls the API in the *beta environment* provided
 ** To use *beta profile* add the following command line argument +
 
 $ java -jar /path/to/trade-bot.jar --spring.profiles.active=beta

 * Dev
 ** Calls the API in the *dev environment* provided
 ** To use *dev profile* add the following command line argument +

 $ java -jar /path/to/trade-bot.jar --spring.profiles.active=dev

[TIP]
====
Check link:https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html[spring boot documentation]
for more details about profiles
====

== Build & Run
This section describes how to build and run the application.
Run the following commands in the root folder of the project.

.Build
[source,bash]
----
$ ./mvnw clean package
----

.Run
[source,bash]
----
$ java -jar target/trade-bot.jar
----

IMPORTANT: By default the application will be running in the port *8081*.

If executed as is it will be dependent to the external API to be available in localhost:8080. Check the <<Profiles>> section
to run it pointing to an external API.

=== Adding Project Lombok Agent
This project uses link:http://projectlombok.org/features/index.html[Project Lombok]
to generate getters and setters etc. Compiling from the command line this
shouldn't cause any problems, but in an IDE you need to add an agent
to the JVM. Full instructions can be found in the Lombok website. The
sign that you need to do this is a lot of compiler errors to do with
missing methods and fields.

== Roadmap - Further improvements
Here's some further improvements to be added in this project

 * Possibility to configure multiple products to quote, buy and sell
 * WebUI to configure the given properties values instead of a standalone running bot
 * WebSocket notifications feed endpoint to notify when a trade action occurs
 * Use state machine to control the application flow
 * Add some Rule Engine such as link:http://drools.jboss.org[Drools] in order to make the trade rules configurable without
  changing the code
 * Add max-retry configuration property to improve the trade rules

== Contributing
TradeBot is released under the non-restrictive Apache 2.0 license, and follows a very standard Github development
process, using Github tracker for issues and merging pull requests into master.
If you want to contribute even something trivial please do not hesitate, but follow the guidelines below.

=== Code of Conduct
This project adheres to the Contributor Covenant link:./docs/code-of-conduct.adoc[code of conduct].
By participating, you are expected to uphold this code. Please report unacceptable behavior to marcos.hgb@gmail.com.