# Configuration for Dev profile

trade:
  api:
    endpoints:
      subscription: wss://rtf.dev.getbux.com/subscriptions/me
      buy-order: https://api.dev.getbux.com/core/16/users/me/trades
      sell-order: https://api.dev.getbux.com/core/16/users/me/portfolio/positions/